### PR TITLE
Add metadata to job template

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by goern** [comment]
@fridex ping

**Comment by fridex** [comment]
> @fridex ping

pong in #45

**Comment by fridex** [comment]
From zuul logs:

```
2018-08-07 07:22:57.077925 | container | app.py
2018-08-07 07:22:57.289479 | container | |  95| ············except:
2018-08-07 07:22:57.289617 | container | |    | [NORMAL] PycodestyleBear (E722):
2018-08-07 07:22:57.295478 | container | |    | E722 do not use bare 'except'
```

**Comment by fridex** [comment]
recheck

**Comment by goern** [comment]
we are getting so good in documenting linkage of things :)

**Pull request merged**
